Converted to yml/updated to 0.11.1 but unable to build due to the following:
checking for libebook-1.2 libebook-contacts-1.2 libedataserver-1.2 libxml-2.0 vala bindings... configure: error: Package requirements were not met: libebook-1.2 libebook-contacts-1.2 libedataserver-1.2 libxml-2.0

error: Package `libebook-1.2' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `libebook-contacts-1.2' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `libedataserver-1.2' not found in specified Vala API directories or GObject-Introspection GIR directories

Consider adjusting the XDG_DATA_DIRS environment variable if you